"""drop_user_id_fk_from_backtest_run

Revision ID: 0ae3f5205846
Revises: bcc3cb621cdb
Create Date: 2026-04-29 11:11:48.531565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ae3f5205846'
down_revision: Union[str, Sequence[str], None] = 'bcc3cb621cdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('backtest_run_user_id_fkey'), 'backtest_run', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('backtest_run_user_id_fkey'), 'backtest_run', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
