"""add_live_investment_tables

Revision ID: 2ee80bd36713
Revises: d8de2e954bb2
Create Date: 2026-06-05 15:31:46.328023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2ee80bd36713'
down_revision: Union[str, Sequence[str], None] = 'd8de2e954bb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy_builder_broker_account',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('broker', sa.String(length=50), nullable=False),
    sa.Column('broker_account_label', sa.String(length=255), nullable=False),
    sa.Column('broker_user_id', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('broker_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'broker', 'broker_account_label', name='uq_strategy_builder_broker_account_user_broker_label')
    )
    op.create_index(op.f('ix_strategy_builder_broker_account_broker'), 'strategy_builder_broker_account', ['broker'], unique=False)
    op.create_index(op.f('ix_strategy_builder_broker_account_broker_user_id'), 'strategy_builder_broker_account', ['broker_user_id'], unique=False)
    op.create_index(op.f('ix_strategy_builder_broker_account_user_id'), 'strategy_builder_broker_account', ['user_id'], unique=False)
    op.create_table('strategy_builder_automate_equity',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('backtest_run_id', sa.UUID(), nullable=True),
    sa.Column('screener_id', sa.UUID(), nullable=True),
    sa.Column('screener_version_id', sa.UUID(), nullable=False),
    sa.Column('strategy_name', sa.String(length=255), nullable=True),
    sa.Column('portfolio_size', sa.Integer(), nullable=False),
    sa.Column('top_rank', sa.Integer(), nullable=True),
    sa.Column('worst_hold_rank', sa.Integer(), nullable=False),
    sa.Column('rebalance_frequency', sa.String(length=20), nullable=False),
    sa.Column('broker_account_id', sa.UUID(), nullable=False),
    sa.Column('broker', sa.String(length=50), nullable=False),
    sa.Column('broker_account_label', sa.String(length=255), nullable=False),
    sa.Column('locked_client_id', sa.String(length=100), nullable=True),
    sa.Column('initial_aum', sa.Float(), nullable=False),
    sa.Column('cash', sa.Float(), nullable=False),
    sa.Column('stock_value', sa.Float(), nullable=False),
    sa.Column('final_aum', sa.Float(), nullable=False),
    sa.Column('pnl', sa.Float(), nullable=False),
    sa.Column('todays_pnl', sa.Float(), nullable=False),
    sa.Column('subscription_active', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PREVIEW_READY', 'PENDING_USER_APPROVAL', 'ACTIVE', 'REBALANCE_READY', 'REBALANCE_PENDING_USER_APPROVAL', 'EXIT_PENDING_USER_APPROVAL', 'EXITED', 'ACCOUNT_MISMATCH', 'FAILED', name='strategy_builder_live_status_enum'), server_default='DRAFT', nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('last_rebalance_date', sa.Date(), nullable=True),
    sa.Column('next_rebalance_date', sa.Date(), nullable=True),
    sa.Column('filters_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('universe_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ranking_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['backtest_run_id'], ['backtest_run.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['broker_account_id'], ['strategy_builder_broker_account.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['screener_id'], ['screeners.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['screener_version_id'], ['screener_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_builder_automate_equity_backtest_run_id'), 'strategy_builder_automate_equity', ['backtest_run_id'], unique=False)
    op.create_index(op.f('ix_strategy_builder_automate_equity_broker_account_id'), 'strategy_builder_automate_equity', ['broker_account_id'], unique=False)
    op.create_index(op.f('ix_strategy_builder_automate_equity_locked_client_id'), 'strategy_builder_automate_equity', ['locked_client_id'], unique=False)
    op.create_index(op.f('ix_strategy_builder_automate_equity_screener_id'), 'strategy_builder_automate_equity', ['screener_id'], unique=False)
    op.create_index(op.f('ix_strategy_builder_automate_equity_screener_version_id'), 'strategy_builder_automate_equity', ['screener_version_id'], unique=False)
    op.create_index(op.f('ix_strategy_builder_automate_equity_status'), 'strategy_builder_automate_equity', ['status'], unique=False)
    op.create_index(op.f('ix_strategy_builder_automate_equity_user_id'), 'strategy_builder_automate_equity', ['user_id'], unique=False)
    op.create_table('strategy_builder_buy_stock',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('automate_equity_ra_id', sa.UUID(), nullable=False),
    sa.Column('tradingsymbol', sa.String(), nullable=False),
    sa.Column('isin', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('triggered_price', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('weightage', sa.Float(), nullable=True),
    sa.Column('actual_qty', sa.Integer(), nullable=True),
    sa.Column('actual_price', sa.Float(), nullable=True),
    sa.Column('actual_amount', sa.Float(), nullable=True),
    sa.Column('stoploss', sa.Float(), nullable=True),
    sa.Column('volatility', sa.Float(), nullable=True),
    sa.Column('order_id', sa.String(), nullable=True),
    sa.Column('circuit', sa.Boolean(), nullable=True),
    sa.Column('updated_in_tradelog', sa.Boolean(), nullable=True),
    sa.Column('auto_code', sa.Boolean(), nullable=True),
    sa.Column('rms_code', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['automate_equity_ra_id'], ['strategy_builder_automate_equity.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_builder_buy_stock_automate_equity_ra_id'), 'strategy_builder_buy_stock', ['automate_equity_ra_id'], unique=False)
    op.create_index(op.f('ix_strategy_builder_buy_stock_order_id'), 'strategy_builder_buy_stock', ['order_id'], unique=False)
    op.create_table('strategy_builder_circuit_stock',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('automate_equity_ra_id', sa.UUID(), nullable=False),
    sa.Column('tradingsymbol', sa.String(), nullable=False),
    sa.Column('isin', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('weightage', sa.Float(), nullable=True),
    sa.Column('actual_qty', sa.Integer(), nullable=True),
    sa.Column('actual_price', sa.Float(), nullable=True),
    sa.Column('actual_amount', sa.Float(), nullable=True),
    sa.Column('stoploss', sa.Float(), nullable=True),
    sa.Column('volatility', sa.Float(), nullable=True),
    sa.Column('order_id', sa.String(), nullable=True),
    sa.Column('updated_in_tradelog', sa.Boolean(), nullable=True),
    sa.Column('auto_code', sa.Boolean(), nullable=True),
    sa.Column('rms_code', sa.String(), nullable=True),
    sa.Column('lower_upper', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['automate_equity_ra_id'], ['strategy_builder_automate_equity.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_builder_circuit_stock_automate_equity_ra_id'), 'strategy_builder_circuit_stock', ['automate_equity_ra_id'], unique=False)
    op.create_index(op.f('ix_strategy_builder_circuit_stock_order_id'), 'strategy_builder_circuit_stock', ['order_id'], unique=False)
    op.create_table('strategy_builder_equitycurve_automate_equity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('automate_equity_ra_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_days', sa.Integer(), nullable=False),
    sa.Column('portfolio_size', sa.Integer(), nullable=True),
    sa.Column('stocks_value', sa.Float(), nullable=True),
    sa.Column('cash', sa.Float(), nullable=True),
    sa.Column('aum', sa.Float(), nullable=True),
    sa.Column('index_price', sa.Float(), nullable=True),
    sa.Column('strategy_roc', sa.Float(), nullable=True),
    sa.Column('index_roc', sa.Float(), nullable=True),
    sa.Column('strategy_daily_return', sa.Float(), nullable=True),
    sa.Column('index_daily_return', sa.Float(), nullable=True),
    sa.Column('strategy_daily_performance', sa.Float(), nullable=True),
    sa.Column('index_daily_performance', sa.Float(), nullable=True),
    sa.Column('compare', sa.Boolean(), nullable=True),
    sa.Column('unrealised_pnl', sa.Float(), nullable=True),
    sa.Column('realised_pnl', sa.Float(), nullable=True),
    sa.Column('total_pnl', sa.Float(), nullable=True),
    sa.Column('winning_trades', sa.Integer(), nullable=True),
    sa.Column('losing_trades', sa.Integer(), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('winning_percent', sa.Float(), nullable=True),
    sa.Column('losing_percent', sa.Float(), nullable=True),
    sa.Column('avg_win', sa.Float(), nullable=True),
    sa.Column('avg_loss', sa.Float(), nullable=True),
    sa.Column('rr', sa.Float(), nullable=True),
    sa.Column('profit_factor', sa.Float(), nullable=True),
    sa.Column('biggest_winning_trade', sa.Float(), nullable=True),
    sa.Column('biggest_losing_trade', sa.Float(), nullable=True),
    sa.Column('expectancy', sa.Float(), nullable=True),
    sa.Column('avg_profit_per_day', sa.Float(), nullable=True),
    sa.Column('max_dd_percent', sa.Float(), nullable=True),
    sa.Column('max_dd_absolute', sa.Float(), nullable=True),
    sa.Column('current_dd_percent', sa.Float(), nullable=True),
    sa.Column('sqn', sa.Float(), nullable=True),
    sa.Column('k_multiple', sa.Float(), nullable=True),
    sa.Column('sharpe', sa.Float(), nullable=True),
    sa.Column('calmar', sa.Float(), nullable=True),
    sa.Column('sortino_ratio', sa.Float(), nullable=True),
    sa.Column('equitycurve_percent', sa.Float(), nullable=True),
    sa.Column('cagr_percent', sa.Float(), nullable=True),
    sa.Column('neg_2sd', sa.Float(), nullable=True),
    sa.Column('equitycurve_avg', sa.Float(), nullable=True),
    sa.Column('pos_2sd', sa.Float(), nullable=True),
    sa.Column('total_charges', sa.Float(), nullable=True),
    sa.Column('rebalance', sa.Boolean(), nullable=True),
    sa.Column('weekly_return', sa.Float(), nullable=True),
    sa.Column('monthly_return', sa.Float(), nullable=True),
    sa.Column('quarterly_return', sa.Float(), nullable=True),
    sa.Column('yearly_return', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['automate_equity_ra_id'], ['strategy_builder_automate_equity.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_builder_equitycurve_automate_equity_automate_equity_ra_id'), 'strategy_builder_equitycurve_automate_equity', ['automate_equity_ra_id'], unique=False)
    op.create_table('strategy_builder_publisher_basket',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('automate_equity_ra_id', sa.UUID(), nullable=False),
    sa.Column('broker_account_id', sa.UUID(), nullable=True),
    sa.Column('broker', sa.String(length=50), nullable=True),
    sa.Column('basket_key', sa.String(length=100), nullable=False),
    sa.Column('basket_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('publisher_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_postback', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['automate_equity_ra_id'], ['strategy_builder_automate_equity.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['broker_account_id'], ['strategy_builder_broker_account.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('basket_key', name='uq_strategy_builder_publisher_basket_key')
    )
    op.create_index(op.f('ix_strategy_builder_publisher_basket_automate_equity_ra_id'), 'strategy_builder_publisher_basket', ['automate_equity_ra_id'], unique=False)
    op.create_index(op.f('ix_strategy_builder_publisher_basket_basket_key'), 'strategy_builder_publisher_basket', ['basket_key'], unique=False)
    op.create_index(op.f('ix_strategy_builder_publisher_basket_broker'), 'strategy_builder_publisher_basket', ['broker'], unique=False)
    op.create_index(op.f('ix_strategy_builder_publisher_basket_broker_account_id'), 'strategy_builder_publisher_basket', ['broker_account_id'], unique=False)
    op.create_table('strategy_builder_sell_stock',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('automate_equity_ra_id', sa.UUID(), nullable=False),
    sa.Column('tradingsymbol', sa.String(), nullable=False),
    sa.Column('isin', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('actual_qty', sa.Integer(), nullable=True),
    sa.Column('actual_price', sa.Float(), nullable=True),
    sa.Column('actual_amount', sa.Float(), nullable=True),
    sa.Column('order_id', sa.String(), nullable=True),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('circuit', sa.Boolean(), nullable=True),
    sa.Column('updated_in_tradelog', sa.Boolean(), nullable=True),
    sa.Column('auto_code', sa.Boolean(), nullable=True),
    sa.Column('rms_code', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['automate_equity_ra_id'], ['strategy_builder_automate_equity.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_builder_sell_stock_automate_equity_ra_id'), 'strategy_builder_sell_stock', ['automate_equity_ra_id'], unique=False)
    op.create_index(op.f('ix_strategy_builder_sell_stock_order_id'), 'strategy_builder_sell_stock', ['order_id'], unique=False)
    op.create_table('strategy_builder_tradelog_automate_equity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('automate_equity_ra_id', sa.UUID(), nullable=False),
    sa.Column('tradingsymbol', sa.String(), nullable=False),
    sa.Column('isin', sa.String(), nullable=False),
    sa.Column('buy_date', sa.Date(), nullable=False),
    sa.Column('sell_date', sa.Date(), nullable=True),
    sa.Column('hold', sa.Integer(), nullable=False),
    sa.Column('weightage', sa.Float(), nullable=True),
    sa.Column('buy_qty', sa.Integer(), nullable=False),
    sa.Column('buy_price', sa.Float(), nullable=False),
    sa.Column('buy_amount', sa.Float(), nullable=False),
    sa.Column('sell_qty', sa.Integer(), nullable=True),
    sa.Column('sell_price', sa.Float(), nullable=True),
    sa.Column('sell_amount', sa.Float(), nullable=True),
    sa.Column('pyramiding', sa.Integer(), nullable=True),
    sa.Column('volatility', sa.Float(), nullable=True),
    sa.Column('ltp', sa.Float(), nullable=True),
    sa.Column('stoploss', sa.Float(), nullable=True),
    sa.Column('risk', sa.Float(), nullable=True),
    sa.Column('risk_percent', sa.Float(), nullable=True),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('unrealised_pnl', sa.Float(), nullable=True),
    sa.Column('realised_pnl', sa.Float(), nullable=True),
    sa.Column('profit_percent', sa.Float(), nullable=True),
    sa.Column('buy_charges', sa.Float(), nullable=True),
    sa.Column('sell_charges', sa.Float(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('buy_order_id', sa.String(), nullable=True),
    sa.Column('sell_order_id', sa.String(), nullable=True),
    sa.Column('pyramiding_data', sa.String(), nullable=True),
    sa.Column('profit_booking_data', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['automate_equity_ra_id'], ['strategy_builder_automate_equity.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_builder_tradelog_automate_equity_automate_equity_ra_id'), 'strategy_builder_tradelog_automate_equity', ['automate_equity_ra_id'], unique=False)
    op.create_index(op.f('ix_strategy_builder_tradelog_automate_equity_buy_order_id'), 'strategy_builder_tradelog_automate_equity', ['buy_order_id'], unique=False)
    op.create_index(op.f('ix_strategy_builder_tradelog_automate_equity_sell_order_id'), 'strategy_builder_tradelog_automate_equity', ['sell_order_id'], unique=False)
    op.drop_index(op.f('ix_broker_orders_basket_id'), table_name='broker_orders')
    op.drop_index(op.f('ix_broker_orders_id'), table_name='broker_orders')
    op.drop_index(op.f('ix_broker_orders_internal_order_id'), table_name='broker_orders')
    op.drop_index(op.f('ix_broker_orders_user_id'), table_name='broker_orders')
    op.drop_index(op.f('ix_broker_orders_zerodha_order_id'), table_name='broker_orders')
    op.drop_table('broker_orders')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broker_orders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('internal_order_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('basket_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('broker', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('zerodha_order_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('exchange', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tradingsymbol', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('transaction_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('order_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('filled_quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('average_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('raw_postback', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('broker_orders_pkey'))
    )
    op.create_index(op.f('ix_broker_orders_zerodha_order_id'), 'broker_orders', ['zerodha_order_id'], unique=False)
    op.create_index(op.f('ix_broker_orders_user_id'), 'broker_orders', ['user_id'], unique=False)
    op.create_index(op.f('ix_broker_orders_internal_order_id'), 'broker_orders', ['internal_order_id'], unique=True)
    op.create_index(op.f('ix_broker_orders_id'), 'broker_orders', ['id'], unique=False)
    op.create_index(op.f('ix_broker_orders_basket_id'), 'broker_orders', ['basket_id'], unique=False)
    op.drop_index(op.f('ix_strategy_builder_tradelog_automate_equity_sell_order_id'), table_name='strategy_builder_tradelog_automate_equity')
    op.drop_index(op.f('ix_strategy_builder_tradelog_automate_equity_buy_order_id'), table_name='strategy_builder_tradelog_automate_equity')
    op.drop_index(op.f('ix_strategy_builder_tradelog_automate_equity_automate_equity_ra_id'), table_name='strategy_builder_tradelog_automate_equity')
    op.drop_table('strategy_builder_tradelog_automate_equity')
    op.drop_index(op.f('ix_strategy_builder_sell_stock_order_id'), table_name='strategy_builder_sell_stock')
    op.drop_index(op.f('ix_strategy_builder_sell_stock_automate_equity_ra_id'), table_name='strategy_builder_sell_stock')
    op.drop_table('strategy_builder_sell_stock')
    op.drop_index(op.f('ix_strategy_builder_publisher_basket_broker_account_id'), table_name='strategy_builder_publisher_basket')
    op.drop_index(op.f('ix_strategy_builder_publisher_basket_broker'), table_name='strategy_builder_publisher_basket')
    op.drop_index(op.f('ix_strategy_builder_publisher_basket_basket_key'), table_name='strategy_builder_publisher_basket')
    op.drop_index(op.f('ix_strategy_builder_publisher_basket_automate_equity_ra_id'), table_name='strategy_builder_publisher_basket')
    op.drop_table('strategy_builder_publisher_basket')
    op.drop_index(op.f('ix_strategy_builder_equitycurve_automate_equity_automate_equity_ra_id'), table_name='strategy_builder_equitycurve_automate_equity')
    op.drop_table('strategy_builder_equitycurve_automate_equity')
    op.drop_index(op.f('ix_strategy_builder_circuit_stock_order_id'), table_name='strategy_builder_circuit_stock')
    op.drop_index(op.f('ix_strategy_builder_circuit_stock_automate_equity_ra_id'), table_name='strategy_builder_circuit_stock')
    op.drop_table('strategy_builder_circuit_stock')
    op.drop_index(op.f('ix_strategy_builder_buy_stock_order_id'), table_name='strategy_builder_buy_stock')
    op.drop_index(op.f('ix_strategy_builder_buy_stock_automate_equity_ra_id'), table_name='strategy_builder_buy_stock')
    op.drop_table('strategy_builder_buy_stock')
    op.drop_index(op.f('ix_strategy_builder_automate_equity_user_id'), table_name='strategy_builder_automate_equity')
    op.drop_index(op.f('ix_strategy_builder_automate_equity_status'), table_name='strategy_builder_automate_equity')
    op.drop_index(op.f('ix_strategy_builder_automate_equity_screener_version_id'), table_name='strategy_builder_automate_equity')
    op.drop_index(op.f('ix_strategy_builder_automate_equity_screener_id'), table_name='strategy_builder_automate_equity')
    op.drop_index(op.f('ix_strategy_builder_automate_equity_locked_client_id'), table_name='strategy_builder_automate_equity')
    op.drop_index(op.f('ix_strategy_builder_automate_equity_broker_account_id'), table_name='strategy_builder_automate_equity')
    op.drop_index(op.f('ix_strategy_builder_automate_equity_backtest_run_id'), table_name='strategy_builder_automate_equity')
    op.drop_table('strategy_builder_automate_equity')
    op.drop_index(op.f('ix_strategy_builder_broker_account_user_id'), table_name='strategy_builder_broker_account')
    op.drop_index(op.f('ix_strategy_builder_broker_account_broker_user_id'), table_name='strategy_builder_broker_account')
    op.drop_index(op.f('ix_strategy_builder_broker_account_broker'), table_name='strategy_builder_broker_account')
    op.drop_table('strategy_builder_broker_account')
    # ### end Alembic commands ###
