"""add broker_orders table

Revision ID: b1921fe0340d
Revises: c3d4e5f6a7b8
Create Date: 2026-05-25 15:11:07.880453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1921fe0340d'
down_revision: Union[str, Sequence[str], None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broker_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('internal_order_id', sa.String(), nullable=False),
    sa.Column('basket_id', sa.String(), nullable=True),
    sa.Column('broker', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('zerodha_order_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('exchange', sa.String(), nullable=False),
    sa.Column('tradingsymbol', sa.String(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('product', sa.String(), nullable=False),
    sa.Column('order_type', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('filled_quantity', sa.Integer(), nullable=True),
    sa.Column('average_price', sa.Float(), nullable=True),
    sa.Column('raw_postback', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_broker_orders_basket_id'), 'broker_orders', ['basket_id'], unique=False)
    op.create_index(op.f('ix_broker_orders_id'), 'broker_orders', ['id'], unique=False)
    op.create_index(op.f('ix_broker_orders_internal_order_id'), 'broker_orders', ['internal_order_id'], unique=True)
    op.create_index(op.f('ix_broker_orders_user_id'), 'broker_orders', ['user_id'], unique=False)
    op.create_index(op.f('ix_broker_orders_zerodha_order_id'), 'broker_orders', ['zerodha_order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_broker_orders_zerodha_order_id'), table_name='broker_orders')
    op.drop_index(op.f('ix_broker_orders_user_id'), table_name='broker_orders')
    op.drop_index(op.f('ix_broker_orders_internal_order_id'), table_name='broker_orders')
    op.drop_index(op.f('ix_broker_orders_id'), table_name='broker_orders')
    op.drop_index(op.f('ix_broker_orders_basket_id'), table_name='broker_orders')
    op.drop_table('broker_orders')
    # ### end Alembic commands ###
