"""drop_screener_user_id_fk

Revision ID: ba68a8e4f9eb
Revises: 0003_uuid_migration
Create Date: 2026-04-24 16:21:43.722856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ba68a8e4f9eb'
down_revision: Union[str, Sequence[str], None] = '0003_uuid_migration'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('backtest_daily_nav_backtest_run_id_trade_date_key'), 'backtest_daily_nav', type_='unique')
    op.drop_index(op.f('ix_bdn_run_id'), table_name='backtest_daily_nav')
    op.create_index(op.f('ix_backtest_daily_nav_backtest_run_id'), 'backtest_daily_nav', ['backtest_run_id'], unique=False)
    op.create_index(op.f('ix_backtest_daily_nav_trade_date'), 'backtest_daily_nav', ['trade_date'], unique=False)
    op.create_unique_constraint('uq_backtest_daily_nav_date', 'backtest_daily_nav', ['backtest_run_id', 'trade_date'])
    op.drop_index(op.f('ix_bde_run_id'), table_name='backtest_drawdown_episode')
    op.create_index(op.f('ix_backtest_drawdown_episode_backtest_run_id'), 'backtest_drawdown_episode', ['backtest_run_id'], unique=False)
    op.drop_index(op.f('ix_bhp_run_id'), table_name='backtest_holding_period')
    op.create_index(op.f('ix_backtest_holding_period_backtest_run_id'), 'backtest_holding_period', ['backtest_run_id'], unique=False)
    op.create_index(op.f('ix_backtest_holding_period_symbol'), 'backtest_holding_period', ['symbol'], unique=False)
    op.drop_constraint(op.f('backtest_monthly_return_backtest_run_id_year_month_key'), 'backtest_monthly_return', type_='unique')
    op.drop_index(op.f('ix_bmr_run_id'), table_name='backtest_monthly_return')
    op.create_index(op.f('ix_backtest_monthly_return_backtest_run_id'), 'backtest_monthly_return', ['backtest_run_id'], unique=False)
    op.create_unique_constraint('uq_backtest_monthly_return_ym', 'backtest_monthly_return', ['backtest_run_id', 'year', 'month'])
    op.drop_index(op.f('ix_brc_date'), table_name='backtest_rebalance_constituent')
    op.drop_index(op.f('ix_brc_run_id'), table_name='backtest_rebalance_constituent')
    op.create_index(op.f('ix_backtest_rebalance_constituent_backtest_run_id'), 'backtest_rebalance_constituent', ['backtest_run_id'], unique=False)
    op.create_index(op.f('ix_backtest_rebalance_constituent_rebalance_date'), 'backtest_rebalance_constituent', ['rebalance_date'], unique=False)
    op.create_index(op.f('ix_backtest_rebalance_constituent_symbol'), 'backtest_rebalance_constituent', ['symbol'], unique=False)
    op.drop_constraint(op.f('backtest_rebalance_event_backtest_run_id_rebalance_date_key'), 'backtest_rebalance_event', type_='unique')
    op.drop_index(op.f('ix_bre_run_id'), table_name='backtest_rebalance_event')
    op.create_index(op.f('ix_backtest_rebalance_event_backtest_run_id'), 'backtest_rebalance_event', ['backtest_run_id'], unique=False)
    op.create_index(op.f('ix_backtest_rebalance_event_rebalance_date'), 'backtest_rebalance_event', ['rebalance_date'], unique=False)
    op.create_unique_constraint('uq_backtest_rebalance_event_date', 'backtest_rebalance_event', ['backtest_run_id', 'rebalance_date'])
    op.drop_constraint(op.f('backtest_run_request_hash_key'), 'backtest_run', type_='unique')
    op.create_index(op.f('ix_backtest_run_id'), 'backtest_run', ['id'], unique=False)
    op.create_index(op.f('ix_backtest_run_request_hash'), 'backtest_run', ['request_hash'], unique=True)
    op.drop_constraint(op.f('backtest_summary_backtest_run_id_key'), 'backtest_summary', type_='unique')
    op.create_index(op.f('ix_backtest_summary_backtest_run_id'), 'backtest_summary', ['backtest_run_id'], unique=True)
    op.alter_column('screener_versions', 'filters_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('screener_versions', 'universe_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('screener_versions', 'ranking_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.create_index(op.f('ix_screener_versions_id'), 'screener_versions', ['id'], unique=False)
    op.create_index(op.f('ix_screeners_id'), 'screeners', ['id'], unique=False)
    op.drop_constraint(op.f('screeners_user_id_fkey'), 'screeners', type_='foreignkey')
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.create_foreign_key(op.f('screeners_user_id_fkey'), 'screeners', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_screeners_id'), table_name='screeners')
    op.drop_index(op.f('ix_screener_versions_id'), table_name='screener_versions')
    op.alter_column('screener_versions', 'ranking_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('screener_versions', 'universe_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('screener_versions', 'filters_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_index(op.f('ix_backtest_summary_backtest_run_id'), table_name='backtest_summary')
    op.create_unique_constraint(op.f('backtest_summary_backtest_run_id_key'), 'backtest_summary', ['backtest_run_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_backtest_run_request_hash'), table_name='backtest_run')
    op.drop_index(op.f('ix_backtest_run_id'), table_name='backtest_run')
    op.create_unique_constraint(op.f('backtest_run_request_hash_key'), 'backtest_run', ['request_hash'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_backtest_rebalance_event_date', 'backtest_rebalance_event', type_='unique')
    op.drop_index(op.f('ix_backtest_rebalance_event_rebalance_date'), table_name='backtest_rebalance_event')
    op.drop_index(op.f('ix_backtest_rebalance_event_backtest_run_id'), table_name='backtest_rebalance_event')
    op.create_index(op.f('ix_bre_run_id'), 'backtest_rebalance_event', ['backtest_run_id'], unique=False)
    op.create_unique_constraint(op.f('backtest_rebalance_event_backtest_run_id_rebalance_date_key'), 'backtest_rebalance_event', ['backtest_run_id', 'rebalance_date'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_backtest_rebalance_constituent_symbol'), table_name='backtest_rebalance_constituent')
    op.drop_index(op.f('ix_backtest_rebalance_constituent_rebalance_date'), table_name='backtest_rebalance_constituent')
    op.drop_index(op.f('ix_backtest_rebalance_constituent_backtest_run_id'), table_name='backtest_rebalance_constituent')
    op.create_index(op.f('ix_brc_run_id'), 'backtest_rebalance_constituent', ['backtest_run_id'], unique=False)
    op.create_index(op.f('ix_brc_date'), 'backtest_rebalance_constituent', ['rebalance_date'], unique=False)
    op.drop_constraint('uq_backtest_monthly_return_ym', 'backtest_monthly_return', type_='unique')
    op.drop_index(op.f('ix_backtest_monthly_return_backtest_run_id'), table_name='backtest_monthly_return')
    op.create_index(op.f('ix_bmr_run_id'), 'backtest_monthly_return', ['backtest_run_id'], unique=False)
    op.create_unique_constraint(op.f('backtest_monthly_return_backtest_run_id_year_month_key'), 'backtest_monthly_return', ['backtest_run_id', 'year', 'month'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_backtest_holding_period_symbol'), table_name='backtest_holding_period')
    op.drop_index(op.f('ix_backtest_holding_period_backtest_run_id'), table_name='backtest_holding_period')
    op.create_index(op.f('ix_bhp_run_id'), 'backtest_holding_period', ['backtest_run_id'], unique=False)
    op.drop_index(op.f('ix_backtest_drawdown_episode_backtest_run_id'), table_name='backtest_drawdown_episode')
    op.create_index(op.f('ix_bde_run_id'), 'backtest_drawdown_episode', ['backtest_run_id'], unique=False)
    op.drop_constraint('uq_backtest_daily_nav_date', 'backtest_daily_nav', type_='unique')
    op.drop_index(op.f('ix_backtest_daily_nav_trade_date'), table_name='backtest_daily_nav')
    op.drop_index(op.f('ix_backtest_daily_nav_backtest_run_id'), table_name='backtest_daily_nav')
    op.create_index(op.f('ix_bdn_run_id'), 'backtest_daily_nav', ['backtest_run_id'], unique=False)
    op.create_unique_constraint(op.f('backtest_daily_nav_backtest_run_id_trade_date_key'), 'backtest_daily_nav', ['backtest_run_id', 'trade_date'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
