"""summary_to_metrics_json

Revision ID: bcc3cb621cdb
Revises: ba68a8e4f9eb
Create Date: 2026-04-28 11:23:03.034466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcc3cb621cdb'
down_revision: Union[str, Sequence[str], None] = 'ba68a8e4f9eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtest_summary', sa.Column('metrics_json', sa.JSON(), nullable=False, server_default='{}'))
    op.drop_column('backtest_summary', 'hit_ratio_vs_benchmark')
    op.drop_column('backtest_summary', 'upside_capture')
    op.drop_column('backtest_summary', 'avg_holding_days')
    op.drop_column('backtest_summary', 'total_return')
    op.drop_column('backtest_summary', 'worst_month')
    op.drop_column('backtest_summary', 'positive_month_pct')
    op.drop_column('backtest_summary', 'annualized_turnover')
    op.drop_column('backtest_summary', 'total_cost_drag')
    op.drop_column('backtest_summary', 'cagr')
    op.drop_column('backtest_summary', 'max_drawdown')
    op.drop_column('backtest_summary', 'downside_capture')
    op.drop_column('backtest_summary', 'avg_turnover')
    op.drop_column('backtest_summary', 'benchmark_cagr')
    op.drop_column('backtest_summary', 'volatility')
    op.drop_column('backtest_summary', 'best_month')
    op.drop_column('backtest_summary', 'sortino')
    op.drop_column('backtest_summary', 'total_rebalances')
    op.drop_column('backtest_summary', 'calmar')
    op.drop_column('backtest_summary', 'avg_churn_pct')
    op.drop_column('backtest_summary', 'benchmark_total_return')
    op.drop_column('backtest_summary', 'excess_cagr')
    op.drop_column('backtest_summary', 'avg_retention_pct')
    op.drop_column('backtest_summary', 'median_holding_days')
    op.drop_column('backtest_summary', 'avg_month')
    op.drop_column('backtest_summary', 'sharpe')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtest_summary', sa.Column('sharpe', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=False))
    op.add_column('backtest_summary', sa.Column('avg_month', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=True))
    op.add_column('backtest_summary', sa.Column('median_holding_days', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=True))
    op.add_column('backtest_summary', sa.Column('avg_retention_pct', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=True))
    op.add_column('backtest_summary', sa.Column('excess_cagr', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=True))
    op.add_column('backtest_summary', sa.Column('benchmark_total_return', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=True))
    op.add_column('backtest_summary', sa.Column('avg_churn_pct', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=True))
    op.add_column('backtest_summary', sa.Column('calmar', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=False))
    op.add_column('backtest_summary', sa.Column('total_rebalances', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('backtest_summary', sa.Column('sortino', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=False))
    op.add_column('backtest_summary', sa.Column('best_month', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=True))
    op.add_column('backtest_summary', sa.Column('volatility', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=False))
    op.add_column('backtest_summary', sa.Column('benchmark_cagr', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=True))
    op.add_column('backtest_summary', sa.Column('avg_turnover', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=True))
    op.add_column('backtest_summary', sa.Column('downside_capture', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=True))
    op.add_column('backtest_summary', sa.Column('max_drawdown', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=False))
    op.add_column('backtest_summary', sa.Column('cagr', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=False))
    op.add_column('backtest_summary', sa.Column('total_cost_drag', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=True))
    op.add_column('backtest_summary', sa.Column('annualized_turnover', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=True))
    op.add_column('backtest_summary', sa.Column('positive_month_pct', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=True))
    op.add_column('backtest_summary', sa.Column('worst_month', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=True))
    op.add_column('backtest_summary', sa.Column('total_return', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=False))
    op.add_column('backtest_summary', sa.Column('avg_holding_days', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=True))
    op.add_column('backtest_summary', sa.Column('upside_capture', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=True))
    op.add_column('backtest_summary', sa.Column('hit_ratio_vs_benchmark', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=True))
    op.drop_column('backtest_summary', 'metrics_json')
    # ### end Alembic commands ###
