"""add heartbeat and celery_task_id

Revision ID: d8de2e954bb2
Revises: b1921fe0340d
Create Date: 2026-05-26 15:54:48.795700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8de2e954bb2'
down_revision: Union[str, Sequence[str], None] = 'b1921fe0340d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtest_run', sa.Column('last_heartbeat_at', sa.DateTime(), nullable=True))
    op.add_column('backtest_run', sa.Column('celery_task_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backtest_run', 'celery_task_id')
    op.drop_column('backtest_run', 'last_heartbeat_at')
    # ### end Alembic commands ###
